import type { Metadata } from "next";
import "../globals.css";
import NavBar from "@/components/ui/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-green-500"
      >
        <div className="container px-10">
          <NavBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
